package models;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentP.proto

public final class StudentP {
    private StudentP() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface StudentProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:StudentProto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 id = 1;</code>
         */
        int getId();

        /**
         * <code>string name = 2;</code>
         */
        java.lang.String getName();
        /**
         * <code>string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>string gender = 3;</code>
         */
        java.lang.String getGender();
        /**
         * <code>string gender = 3;</code>
         */
        com.google.protobuf.ByteString
        getGenderBytes();

        /**
         * <code>string faculty = 4;</code>
         */
        java.lang.String getFaculty();
        /**
         * <code>string faculty = 4;</code>
         */
        com.google.protobuf.ByteString
        getFacultyBytes();

        /**
         * <code>bytes photo = 5;</code>
         */
        com.google.protobuf.ByteString getPhoto();

        /**
         * <code>repeated string course = 6;</code>
         */
        java.util.List<java.lang.String>
        getCourseList();
        /**
         * <code>repeated string course = 6;</code>
         */
        int getCourseCount();
        /**
         * <code>repeated string course = 6;</code>
         */
        java.lang.String getCourse(int index);
        /**
         * <code>repeated string course = 6;</code>
         */
        com.google.protobuf.ByteString
        getCourseBytes(int index);

        /**
         * <code>string grades = 7;</code>
         */
        java.lang.String getGrades();
        /**
         * <code>string grades = 7;</code>
         */
        com.google.protobuf.ByteString
        getGradesBytes();
    }
    /**
     * Protobuf type {@code StudentProto}
     */
    public  static final class StudentProto extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:StudentProto)
            StudentProtoOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use StudentProto.newBuilder() to construct.
        private StudentProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private StudentProto() {
            name_ = "";
            gender_ = "";
            faculty_ = "";
            photo_ = com.google.protobuf.ByteString.EMPTY;
            course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            grades_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private StudentProto(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            id_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            gender_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            faculty_ = s;
                            break;
                        }
                        case 42: {

                            photo_ = input.readBytes();
                            break;
                        }
                        case 50: {
                            java.lang.String s = input.readStringRequireUtf8();
                            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                                course_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000020;
                            }
                            course_.add(s);
                            break;
                        }
                        case 58: {
                            java.lang.String s = input.readStringRequireUtf8();

                            grades_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000020) != 0)) {
                    course_ = course_.getUnmodifiableView();
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return StudentP.internal_static_StudentProto_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return StudentP.internal_static_StudentProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            StudentP.StudentProto.class, StudentP.StudentProto.Builder.class);
        }

        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 1;
        private int id_;
        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
            return id_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object name_;
        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }
        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int GENDER_FIELD_NUMBER = 3;
        private volatile java.lang.Object gender_;
        /**
         * <code>string gender = 3;</code>
         */
        public java.lang.String getGender() {
            java.lang.Object ref = gender_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                gender_ = s;
                return s;
            }
        }
        /**
         * <code>string gender = 3;</code>
         */
        public com.google.protobuf.ByteString
        getGenderBytes() {
            java.lang.Object ref = gender_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                gender_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FACULTY_FIELD_NUMBER = 4;
        private volatile java.lang.Object faculty_;
        /**
         * <code>string faculty = 4;</code>
         */
        public java.lang.String getFaculty() {
            java.lang.Object ref = faculty_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                faculty_ = s;
                return s;
            }
        }
        /**
         * <code>string faculty = 4;</code>
         */
        public com.google.protobuf.ByteString
        getFacultyBytes() {
            java.lang.Object ref = faculty_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                faculty_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PHOTO_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString photo_;
        /**
         * <code>bytes photo = 5;</code>
         */
        public com.google.protobuf.ByteString getPhoto() {
            return photo_;
        }

        public static final int COURSE_FIELD_NUMBER = 6;
        private com.google.protobuf.LazyStringList course_;
        /**
         * <code>repeated string course = 6;</code>
         */
        public com.google.protobuf.ProtocolStringList
        getCourseList() {
            return course_;
        }
        /**
         * <code>repeated string course = 6;</code>
         */
        public int getCourseCount() {
            return course_.size();
        }
        /**
         * <code>repeated string course = 6;</code>
         */
        public java.lang.String getCourse(int index) {
            return course_.get(index);
        }
        /**
         * <code>repeated string course = 6;</code>
         */
        public com.google.protobuf.ByteString
        getCourseBytes(int index) {
            return course_.getByteString(index);
        }

        public static final int GRADES_FIELD_NUMBER = 7;
        private volatile java.lang.Object grades_;
        /**
         * <code>string grades = 7;</code>
         */
        public java.lang.String getGrades() {
            java.lang.Object ref = grades_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                grades_ = s;
                return s;
            }
        }
        /**
         * <code>string grades = 7;</code>
         */
        public com.google.protobuf.ByteString
        getGradesBytes() {
            java.lang.Object ref = grades_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                grades_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0) {
                output.writeInt32(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (!getGenderBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gender_);
            }
            if (!getFacultyBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, faculty_);
            }
            if (!photo_.isEmpty()) {
                output.writeBytes(5, photo_);
            }
            for (int i = 0; i < course_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, course_.getRaw(i));
            }
            if (!getGradesBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, grades_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, id_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (!getGenderBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gender_);
            }
            if (!getFacultyBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, faculty_);
            }
            if (!photo_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, photo_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < course_.size(); i++) {
                    dataSize += computeStringSizeNoTag(course_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getCourseList().size();
            }
            if (!getGradesBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, grades_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof StudentP.StudentProto)) {
                return super.equals(obj);
            }
            StudentP.StudentProto other = (StudentP.StudentProto) obj;

            if (getId()
                    != other.getId()) return false;
            if (!getName()
                    .equals(other.getName())) return false;
            if (!getGender()
                    .equals(other.getGender())) return false;
            if (!getFaculty()
                    .equals(other.getFaculty())) return false;
            if (!getPhoto()
                    .equals(other.getPhoto())) return false;
            if (!getCourseList()
                    .equals(other.getCourseList())) return false;
            if (!getGrades()
                    .equals(other.getGrades())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + GENDER_FIELD_NUMBER;
            hash = (53 * hash) + getGender().hashCode();
            hash = (37 * hash) + FACULTY_FIELD_NUMBER;
            hash = (53 * hash) + getFaculty().hashCode();
            hash = (37 * hash) + PHOTO_FIELD_NUMBER;
            hash = (53 * hash) + getPhoto().hashCode();
            if (getCourseCount() > 0) {
                hash = (37 * hash) + COURSE_FIELD_NUMBER;
                hash = (53 * hash) + getCourseList().hashCode();
            }
            hash = (37 * hash) + GRADES_FIELD_NUMBER;
            hash = (53 * hash) + getGrades().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static StudentP.StudentProto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static StudentP.StudentProto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static StudentP.StudentProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static StudentP.StudentProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static StudentP.StudentProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static StudentP.StudentProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static StudentP.StudentProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static StudentP.StudentProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static StudentP.StudentProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static StudentP.StudentProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static StudentP.StudentProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static StudentP.StudentProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(StudentP.StudentProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code StudentProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:StudentProto)
                StudentP.StudentProtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return StudentP.internal_static_StudentProto_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return StudentP.internal_static_StudentProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                StudentP.StudentProto.class, StudentP.StudentProto.Builder.class);
            }

            // Construct using StudentP.StudentProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                id_ = 0;

                name_ = "";

                gender_ = "";

                faculty_ = "";

                photo_ = com.google.protobuf.ByteString.EMPTY;

                course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000020);
                grades_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return StudentP.internal_static_StudentProto_descriptor;
            }

            @java.lang.Override
            public StudentP.StudentProto getDefaultInstanceForType() {
                return StudentP.StudentProto.getDefaultInstance();
            }

            @java.lang.Override
            public StudentP.StudentProto build() {
                StudentP.StudentProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public StudentP.StudentProto buildPartial() {
                StudentP.StudentProto result = new StudentP.StudentProto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.id_ = id_;
                result.name_ = name_;
                result.gender_ = gender_;
                result.faculty_ = faculty_;
                result.photo_ = photo_;
                if (((bitField0_ & 0x00000020) != 0)) {
                    course_ = course_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000020);
                }
                result.course_ = course_;
                result.grades_ = grades_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof StudentP.StudentProto) {
                    return mergeFrom((StudentP.StudentProto)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(StudentP.StudentProto other) {
                if (other == StudentP.StudentProto.getDefaultInstance()) return this;
                if (other.getId() != 0) {
                    setId(other.getId());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getGender().isEmpty()) {
                    gender_ = other.gender_;
                    onChanged();
                }
                if (!other.getFaculty().isEmpty()) {
                    faculty_ = other.faculty_;
                    onChanged();
                }
                if (other.getPhoto() != com.google.protobuf.ByteString.EMPTY) {
                    setPhoto(other.getPhoto());
                }
                if (!other.course_.isEmpty()) {
                    if (course_.isEmpty()) {
                        course_ = other.course_;
                        bitField0_ = (bitField0_ & ~0x00000020);
                    } else {
                        ensureCourseIsMutable();
                        course_.addAll(other.course_);
                    }
                    onChanged();
                }
                if (!other.getGrades().isEmpty()) {
                    grades_ = other.grades_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                StudentP.StudentProto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (StudentP.StudentProto) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private int id_ ;
            /**
             * <code>int32 id = 1;</code>
             */
            public int getId() {
                return id_;
            }
            /**
             * <code>int32 id = 1;</code>
             */
            public Builder setId(int value) {

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";
            /**
             * <code>string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }
            /**
             * <code>string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object gender_ = "";
            /**
             * <code>string gender = 3;</code>
             */
            public java.lang.String getGender() {
                java.lang.Object ref = gender_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    gender_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string gender = 3;</code>
             */
            public com.google.protobuf.ByteString
            getGenderBytes() {
                java.lang.Object ref = gender_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    gender_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string gender = 3;</code>
             */
            public Builder setGender(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                gender_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string gender = 3;</code>
             */
            public Builder clearGender() {

                gender_ = getDefaultInstance().getGender();
                onChanged();
                return this;
            }
            /**
             * <code>string gender = 3;</code>
             */
            public Builder setGenderBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                gender_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object faculty_ = "";
            /**
             * <code>string faculty = 4;</code>
             */
            public java.lang.String getFaculty() {
                java.lang.Object ref = faculty_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    faculty_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string faculty = 4;</code>
             */
            public com.google.protobuf.ByteString
            getFacultyBytes() {
                java.lang.Object ref = faculty_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    faculty_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string faculty = 4;</code>
             */
            public Builder setFaculty(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                faculty_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string faculty = 4;</code>
             */
            public Builder clearFaculty() {

                faculty_ = getDefaultInstance().getFaculty();
                onChanged();
                return this;
            }
            /**
             * <code>string faculty = 4;</code>
             */
            public Builder setFacultyBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                faculty_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString photo_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes photo = 5;</code>
             */
            public com.google.protobuf.ByteString getPhoto() {
                return photo_;
            }
            /**
             * <code>bytes photo = 5;</code>
             */
            public Builder setPhoto(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                photo_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes photo = 5;</code>
             */
            public Builder clearPhoto() {

                photo_ = getDefaultInstance().getPhoto();
                onChanged();
                return this;
            }

            private com.google.protobuf.LazyStringList course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            private void ensureCourseIsMutable() {
                if (!((bitField0_ & 0x00000020) != 0)) {
                    course_ = new com.google.protobuf.LazyStringArrayList(course_);
                    bitField0_ |= 0x00000020;
                }
            }
            /**
             * <code>repeated string course = 6;</code>
             */
            public com.google.protobuf.ProtocolStringList
            getCourseList() {
                return course_.getUnmodifiableView();
            }
            /**
             * <code>repeated string course = 6;</code>
             */
            public int getCourseCount() {
                return course_.size();
            }
            /**
             * <code>repeated string course = 6;</code>
             */
            public java.lang.String getCourse(int index) {
                return course_.get(index);
            }
            /**
             * <code>repeated string course = 6;</code>
             */
            public com.google.protobuf.ByteString
            getCourseBytes(int index) {
                return course_.getByteString(index);
            }
            /**
             * <code>repeated string course = 6;</code>
             */
            public Builder setCourse(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureCourseIsMutable();
                course_.set(index, value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string course = 6;</code>
             */
            public Builder addCourse(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureCourseIsMutable();
                course_.add(value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string course = 6;</code>
             */
            public Builder addAllCourse(
                    java.lang.Iterable<java.lang.String> values) {
                ensureCourseIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, course_);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string course = 6;</code>
             */
            public Builder clearCourse() {
                course_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000020);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string course = 6;</code>
             */
            public Builder addCourseBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureCourseIsMutable();
                course_.add(value);
                onChanged();
                return this;
            }

            private java.lang.Object grades_ = "";
            /**
             * <code>string grades = 7;</code>
             */
            public java.lang.String getGrades() {
                java.lang.Object ref = grades_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    grades_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string grades = 7;</code>
             */
            public com.google.protobuf.ByteString
            getGradesBytes() {
                java.lang.Object ref = grades_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    grades_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string grades = 7;</code>
             */
            public Builder setGrades(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                grades_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string grades = 7;</code>
             */
            public Builder clearGrades() {

                grades_ = getDefaultInstance().getGrades();
                onChanged();
                return this;
            }
            /**
             * <code>string grades = 7;</code>
             */
            public Builder setGradesBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                grades_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:StudentProto)
        }

        // @@protoc_insertion_point(class_scope:StudentProto)
        private static final StudentP.StudentProto DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new StudentP.StudentProto();
        }

        public static StudentP.StudentProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<StudentProto>
                PARSER = new com.google.protobuf.AbstractParser<StudentProto>() {
            @java.lang.Override
            public StudentProto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new StudentProto(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<StudentProto> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<StudentProto> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public StudentP.StudentProto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_StudentProto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_StudentProto_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016StudentP.proto\"x\n\014StudentProto\022\n\n\002id\030\001" +
                        " \001(\005\022\014\n\004name\030\002 \001(\t\022\016\n\006gender\030\003 \001(\t\022\017\n\007fa" +
                        "culty\030\004 \001(\t\022\r\n\005photo\030\005 \001(\014\022\016\n\006course\030\006 \003" +
                        "(\t\022\016\n\006grades\030\007 \001(\tb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_StudentProto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_StudentProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_StudentProto_descriptor,
                new java.lang.String[] { "Id", "Name", "Gender", "Faculty", "Photo", "Course", "Grades", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}